### ISSUE TITLE
Make use of onChange

### ISSUE THREAD

**Issue by AndrewIsh** [networknt/angular-schema-form-ui-ace#1]
Currently this does not appear to support the 'onChange' form property, it would be useful if it did.

**Comment by stevehu** [comment]
It is easy to add onChange but I don't know how to handle it within the schema form. All of my use cases won't care about the onChange but only need to capture the last snapshot when submit button is clicked. Could you please explain your use case a little bit more?

**Comment by AndrewIsh** [comment]
Thanks for your reply. Apologies for not getting back to you sooner. I take your point. In fact, since posting this issue I no longer have this requirement, so I'll close.

Cheers!
